const products = [
    {
      id: 1,
      imgUrl:
        'https://images.meesho.com/images/products/535078297/lmluv_512.avif?width=360',
      name: 'Men Solid Black T-Shirt',
      description: 'Premium cotton solid black t-shirt for everyday wear.',
      rating: 2.4,
      price: 999,
      discountedPrice: 699,
      discountPercentage: 30,
      gender: 'male',
      category: 'Casual',
    },
    {
      id: 2,
      imgUrl:
        'https://images.meesho.com/images/products/703705468/htv0a_512.avif?width=360',
      name: 'Women Graphic Printed T-Shirt',
      description: 'Trendy graphic printed t-shirt with soft fabric.',
      rating: 5,
      price: 1099,
      discountedPrice: 769,
      discountPercentage: 30,
      gender: 'female',
      category: 'Casual',
    },
    {
      id: 3,
      imgUrl:
        'https://images.meesho.com/images/products/549671878/tkjh5_512.avif?width=360',
      name: 'Men Oversized T-Shirt',
      description: 'Comfortable oversized t-shirt with relaxed fit.',
      rating: 3.6,
      price: 1499,
      discountedPrice: 1049,
      discountPercentage: 30,
      gender: 'male',
      category: 'Semi-Casual',
    },
    {
      id: 4,
      imgUrl:
        'https://images.meesho.com/images/products/656322565/k0ldw_512.avif?width=360',
      name: 'Women Polo Neck T-Shirt',
      description: 'Stylish polo neck t-shirt suitable for casual wear.',
      rating: 4.3,
      price: 1299,
      discountedPrice: 909,
      discountPercentage: 30,
      gender: 'female',
      category: 'Semi-Casual',
    },
    {
      id: 5,
      imgUrl:
        'https://images.meesho.com/images/products/541757386/nnekb_512.avif?width=360',
      name: 'Men Striped T-Shirt',
      description: 'Classic striped t-shirt made with breathable fabric.',
      rating: 4.2,
      price: 1199,
      discountedPrice: 839,
      discountPercentage: 30,
      gender: 'male',
      category: 'Casual',
    },
    {
      id: 6,
      imgUrl:
        'https://images.meesho.com/images/products/557038569/ymub1_512.avif?width=360',
      name: 'Women Round Neck Cotton T-Shirt',
      description: 'Soft cotton round neck t-shirt for daily comfort.',
      rating: 1.4,
      price: 899,
      discountedPrice: 629,
      discountPercentage: 30,
      gender: 'female',
      category: 'Casual',
    },
    {
      id: 7,
      imgUrl:
        'https://images.meesho.com/images/products/382857528/wl5e3_512.avif?width=360',
      name: 'Men Plain White T-Shirt',
      description: 'Simple and clean white t-shirt with premium finish.',
      rating: 4.1,
      price: 799,
      discountedPrice: 559,
      discountPercentage: 30,
      gender: 'male',
      category: 'Formal',
    },
    {
      id: 8,
      imgUrl:
        'https://images.meesho.com/images/products/570817984/i4kzb_512.avif?width=360',
      name: 'Women Pastel Color T-Shirt',
      description: 'Pastel shade t-shirt with smooth and breathable fabric.',
      rating: 4.3,
      price: 999,
      discountedPrice: 699,
      discountPercentage: 30,
      gender: 'female',
      category: 'Semi-Casual',
    },
    {
      id: 9,
      imgUrl:
        'https://images.meesho.com/images/products/710962490/qtwdf_512.avif?width=360',
      name: 'Men Gym Wear T-Shirt',
      description: 'Moisture-wicking t-shirt perfect for workouts.',
      rating: 4.5,
      price: 1399,
      discountedPrice: 979,
      discountPercentage: 30,
      gender: 'male',
      category: 'Sportswear',
    },
    {
      id: 10,
      imgUrl:
        'https://images.meesho.com/images/products/520773211/loof0_512.avif?width=360',
      name: 'Women Crop T-Shirt',
      description: 'Stylish crop t-shirt for modern casual look.',
      rating: 4.2,
      price: 899,
      discountedPrice: 629,
      discountPercentage: 30,
      gender: 'female',
      category: 'Party-wear',
    },
  
    {
      id: 11,
      imgUrl:
        'https://images.meesho.com/images/products/4681169/1_512.avif?width=360',
      name: 'Men Formal Blue Shirt',
      description: 'Elegant formal shirt suitable for office wear.',
      rating: 4.4,
      price: 1999,
      discountedPrice: 1399,
      discountPercentage: 30,
      gender: 'male',
      category: 'Formal',
    },
    {
      id: 12,
      imgUrl:
        'https://images.meesho.com/images/products/415127560/wxtgy_512.avif?width=360',
      name: 'Women Formal White Shirt',
      description: 'Classic white formal shirt with tailored fit.',
      rating: 4.6,
      price: 1899,
      discountedPrice: 1329,
      discountPercentage: 30,
      gender: 'female',
      category: 'Formal',
    },
    {
      id: 13,
      imgUrl:
        'https://images.meesho.com/images/products/700614894/hdjef_512.avif?width=360',
      name: 'Men Party Wear Shirt',
      description: 'Stylish party wear shirt with glossy finish.',
      rating: 4.7,
      price: 2499,
      discountedPrice: 1749,
      discountPercentage: 30,
      gender: 'male',
      category: 'Party-wear',
    },
    {
      id: 14,
      imgUrl:
        'https://images.meesho.com/images/products/228360042/pgx9z_512.avif?width=360',
      name: 'Women Party Wear Top',
      description: 'Trendy top designed for evening parties.',
      rating: 4.5,
      price: 2199,
      discountedPrice: 1539,
      discountPercentage: 30,
      gender: 'female',
      category: 'Party-wear',
    },
    {
      id: 15,
      imgUrl:
        'https://images.meesho.com/images/products/692050872/wcf77_512.avif?width=360',
      name: 'Men Semi Casual Shirt',
      description: 'Perfect balance between formal and casual style.',
      rating: 4.1,
      price: 1799,
      discountedPrice: 1259,
      discountPercentage: 30,
      gender: 'male',
      category: 'Semi-Casual',
    },
    {
      id: 16,
      imgUrl:
        'https://images.meesho.com/images/products/489735100/wkkfk_512.avif?width=360',
      name: 'Women Semi Casual Top',
      description: 'Comfortable semi-casual top for daily outings.',
      rating: 4.0,
      price: 1599,
      discountedPrice: 1119,
      discountPercentage: 30,
      gender: 'female',
      category: 'Semi-Casual',
    },
    {
      id: 17,
      imgUrl:
        'https://images.meesho.com/images/products/527114801/6llf2_512.avif?width=360',
      name: 'Men Casual Printed Shirt',
      description: 'Relaxed casual shirt with modern prints.',
      rating: 3.9,
      price: 1499,
      discountedPrice: 1049,
      discountPercentage: 30,
      gender: 'male',
      category: 'Casual',
    },
    {
      id: 18,
      imgUrl:
        'https://images.meesho.com/images/products/6356797/b64d3_512.avif?width=360',
      name: 'Women Casual Tunic',
      description: 'Lightweight tunic perfect for casual wear.',
      rating: 4.2,
      price: 1699,
      discountedPrice: 1189,
      discountPercentage: 30,
      gender: 'female',
      category: 'Casual',
    },
    {
      id: 19,
      imgUrl:
        'https://images.meesho.com/images/products/646346886/sjsbu_512.avif?width=360',
      name: 'Men Sports Training T-Shirt',
      description: 'Breathable sports t-shirt for intense workouts.',
      rating: 4.6,
      price: 1299,
      discountedPrice: 909,
      discountPercentage: 30,
      gender: 'male',
      category: 'Sportswear',
    },
    {
      id: 20,
      imgUrl:
        'https://images.meesho.com/images/products/711809837/qdgur_512.avif?width=360',
      name: 'Women Sports Active Tee',
      description: 'Flexible and sweat-resistant activewear tee.',
      rating: 4.4,
      price: 1199,
      discountedPrice: 839,
      discountPercentage: 30,
      gender: 'female',
      category: 'Sportswear',
    },
    {
      id: 21,
      imgUrl:
        'https://images.meesho.com/images/products/433761022/fr69d_512.avif?width=360',
      name: 'Men Party Jacket',
      description: 'Bold party jacket for special occasions.',
      rating: 4.8,
      price: 3499,
      discountedPrice: 2449,
      discountPercentage: 30,
      gender: 'male',
      category: 'Party-wear',
    },
    {
      id: 22,
      imgUrl:
        'https://images.meesho.com/images/products/389517594/rn9vm_512.avif?width=360',
      name: 'Women Party Blazer',
      description: 'Elegant blazer for party and formal events.',
      rating: 4.7,
      price: 3299,
      discountedPrice: 2309,
      discountPercentage: 30,
      gender: 'female',
      category: 'Party-wear',
    },
    {
      id: 23,
      imgUrl:
        'https://images.meesho.com/images/products/680309624/hw3fm_512.avif?width=360',
      name: 'Men Formal Grey Shirt',
      description: 'Slim-fit formal shirt with premium fabric.',
      rating: 4.3,
      price: 2099,
      discountedPrice: 1469,
      discountPercentage: 30,
      gender: 'male',
      category: 'Formal',
    },
    {
      id: 24,
      imgUrl:
        'https://images.meesho.com/images/products/568326899/8gmje_512.avif?width=360',
      name: 'Women Formal Office Top',
      description: 'Professional office top with clean design.',
      rating: 4.5,
      price: 1999,
      discountedPrice: 1399,
      discountPercentage: 30,
      gender: 'female',
      category: 'Formal',
    },
    {
      id: 25,
      imgUrl:
        'https://images.meesho.com/images/products/692779595/ibmzf_512.avif?width=360',
      name: 'Unisex Casual Hoodie',
      description: 'Comfortable hoodie suitable for all genders.',
      rating: 4.6,
      price: 2499,
      discountedPrice: 1749,
      discountPercentage: 30,
      gender: 'male',
      category: 'Casual',
    },
  ];
//   export const data1=[]
  export default products;
  